"""Second migration

Revision ID: 635c46c6e283
Revises: c7b1c8db98df
Create Date: 2025-08-25 19:29:57.304623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635c46c6e283'
down_revision = 'c7b1c8db98df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
